version: '3.7'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.nginx
    container_name: app
    hostname: app
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:8000
    restart: on-failure
    volumes:
      #- ./staticdata:/home/app/portal/static
      - ./staticdata:/home/app/static
    expose:
      - 8000
#    ports:
#      - 8000:8000
    env_file:
      - ./app/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=portal.settings.local_postgres_nginx
    networks:
      - public
      - private
    depends_on:
      - db
  
  db:
    build: ./db
    container_name: db
    hostname: db
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data/
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/opt/sql.d:/opt/sql.d
    env_file:
      - ./db/.env.dev
    ports:
      - 5432:5432
    networks:
      - private

  nginx:
    build: ./nginx
    container_name: nginx
    hostname: nginx
    restart: on-failure
    volumes:
      - ./nginx/log:/var/log/nginx
      #- ./staticdata:/home/app/portal/static
      - ./staticdata:/home/app/static
    ports:
      - 9999:80
    networks:
      - public
    depends_on:
      - app

volumes:
  postgres_data:
    driver: local
  staticdata:
    driver: local

networks:
  public:
    driver: bridge
  private:
    driver: bridge
