version: '3.7'

services:
  app:
    build: ./app
    container_name: app
    hostname: app
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:8000
    restart: on-failure
    volumes:
      - ./static:/home/app/static
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=portal.settings.local_postgres_nginx
    networks:
      - public
      - private
    depends_on:
      - db
  
  db:
    build: ./db
    container_name: db
    hostname: db
    restart: on-failure
    tty: true
    volumes:
#      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - ./db/.env.dev
    ports:
      - 5432:5432
    networks:
      - private

  nginx:
    build: ./nginx
    container_name: nginx
    hostname: nginx
    restart: on-failure
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./static:/static
    ports:
      - 9999:80
    networks:
      - public
    depends_on:
      - app

volumes:
#  postgres_data:
#  driver: local
  static:
    driver: local

networks:
  public:
    driver: bridge
  private:
    driver: bridge
